React Capstone: Metrics webapp
Jmagero/metrics-webapp pull request #1
Opened 2021-09-17 02:55 UTC by Jmagero

- [x] Project is a single page application (SPA) built with React and Redux.
- [x] Data is retrieved from the API should be stored in the Redux store.
- [x] Filtered data that you retrieve from the API using a Filter stateless component.
- [X] Every page (the main page and the pages for each item) should have a unique route within the SPA.
- [ ] The project should be deployed and accessible online (add a link to the online version of your app to your README file).
- [ ] Create unit tests for pure functions in your Redux code.
- [ ] Create integration tests for your application using the React Testing Library.
- [ ] You may need to mock the access to the API, so that your tests don't send actual requests.
- [ ] You may need to mock the connection to the Redux Store.

2021-09-17 05:12 UTC, oloomoses requested changes
Hi @Jmagero, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] There are no items displayed when the app is loaded. Instead, I only see a dropdown menu of names. The `home` page should display a  list of browsable items that can be filtered by category. When the item is clicked I should be redirected to the details page. Kindly take a look at this [project](https://the-catalystmc.github.io/crypto-market-cap-app/#/currencies) for inspiration. 
- [ ] Kindly ensure that the app is deployed and the live link is provided in the readme as per the project requirements.
- [ ] Kindly add a video presentation for the project as per the requirements.
- [ ] Your design does not match the given one. Kindly add all the icons in the navigation bar even if they are not functional.

_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 21:05 UTC, Jmagero commented
- [x]  There are no items displayed when the app is loaded. Instead, I only see a dropdown menu of names. The home page should display a list of browsable items that can be filtered by category. When the item is clicked I should be redirected to the details page. Kindly take a look at this project for inspiration.
- [x]  Kindly ensure that the app is deployed and the live link is provided in the readme as per the project requirements.
- [x]  Kindly add a video presentation for the project as per the requirements.
- [x]  Your design does not match the given one. Kindly add all the icons in the navigation bar even if they are not functional.

2021-09-18 13:57 UTC, Georjane commented on README.md
> +## Acknowledgments
- [ ] Hi @Jmagero, just like the previous reviewer mentioned, please add to the "Acknowledgements" section or similar section appropriate credits to Nelson Sakwa the author of the original design, as required by the Creative Commons License.

2021-09-18 14:02 UTC, Georjane requested changes
### Hello, @Jmagero, ✋🏽 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-18 14:02 UTC, Georjane commented on src/App.js
> +const App = () => {
- [ ] Your Home page should have a  list of categories that could be filtered using given parameters, e.g. category name. See this very [good example](https://the-catalystmc.github.io/crypto-market-cap-app/#/currencies) provided by the previous code reviewer. You can filter yours using any parameter of your choice

2021-09-18 19:36 UTC, Jmagero commented
- [x] Add to the "Acknowledgements" section or similar section appropriate credits to Nelson Sakwa the author of the original design, as required by the Creative Commons License.
- [x] Added a list of categories that could be filtered using given parameters

2021-09-19 01:23 UTC, oxenprogrammer requested changes
Hi @Jmagero , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. :muscle:


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Consider the optional changes nice to have features and only work on them when you have satisfied the required changes_
- [ ] There are currently errors on the console in relation to `PropTypes` required fields. Let us try to resolve these as well.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-19 01:23 UTC, oxenprogrammer commented on README.md
> +[Github](https://jmagero.github.io/)
**Changes Required**
- [ ] The live demo is currently not working. This is required since it's a proof of concept that you can host an application on production. _Remember, if it wasn't shipped, it never happened_.

2021-09-19 02:06 UTC, Jmagero commented
- [x] Add live demo

2021-09-19 06:08 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-03 00:09 UTC, merged